### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by AName4** [aldacco/drive-login#10]
Hi @aldacco,

Edit: I had an issue which I solved now successfully. I would have posted the solution, but I didnt know what it was. It just worked suddenly. Therefore this issue can be closed.

Nevertheless thank you very much for your effort to keep this running and thank you for all your help here :)

**Comment by pordeciralgo** [comment]
Hi @AName4 ,

Could you post screenshots* of your Google configuration (URLs, scopes, public/testing...). I'm getting that same Error 400: redirect_uri_mismatch and I don't know how to fix it.

Thank you in advance

*Of course, remove/blur all sensitive data

**Comment by aldacco** [comment]
> Hi @AName4 ,
> 
> Could you post screenshots* of your Google configuration (URLs, scopes, public/testing...). I'm getting that same Error 400: redirect_uri_mismatch and I don't know how to fix it.
> 
> Thank you in advance
> 
> *Of course, remove/blur all sensitive data

I have updated the readme, added video tutorials.

**Comment by pordeciralgo** [comment]
Thanks @aldacco !

I had set it up properly, what failed was i needed to redeploy after setting the id/secret. [facepalm here]

**Comment by Anshbhai27** [comment]
![photo_2024-09-14_15-33-35](https://github.com/user-attachments/assets/87e54eff-3322-4c2c-a68c-01918ea7268b)
after successfully give permison but dont know why showing this ???
