### ISSUE TITLE
please make a video 

### ISSUE THREAD

**Issue by iamknightrohit** [aldacco/drive-login#11]
i dont understand anything just make a simple video because your steps are unclear and difficult to understand.
![Screenshot (12)](https://github.com/user-attachments/assets/538e49b8-fb12-4c7e-bad9-7871ebf8e7fc)
my vercel link
https://drive-login.vercel.app/

**Comment by kyilintun2024** [comment]
I also faced this error too.
May be i lacked of knowledge.
Please make a video tutorials.
Thanks for your time.

**Comment by aldacco** [comment]
> I also faced this error too. May be i lacked of knowledge. Please make a video tutorials. Thanks for your time.

I have added videos for each step, and this specific error may be caused by:
https://github.com/aldacco/drive-login/tree/main?tab=readme-ov-file#2-modify-add-on-settings
> [!WARNING]  
> **Do not include the trailing slash (`/`)** at the end of the URL (e.g., `https://your-app.example.vercel.app/`). Adding the trailing slash may cause connection issues with the server, and the add-on might not function properly.
>
> Make sure the URL is set exactly as: **`https://your-app.example.vercel.app`**.

**Comment by kyilintun2024** [comment]
@aldacco 
Thank you so much, I have done by what you show in tutorial video and remove ( / ) is working now.
My kodi is back.
