### ISSUE TITLE
Error 403:access_denied

### ISSUE THREAD

**Issue by wildgamharsh** [aldacco/drive-login#15]
![image](https://github.com/user-attachments/assets/3ac3d456-61a5-4714-b7b1-6838de93ecd6)
please help me fix this issue

**Comment by omardtd** [comment]
yeah same issue here

**Comment by omardtd** [comment]
To fix this issue for me was this simple:

1. Go to https://console.developers.google.com/
2. On the top left beside the words "Google APIs" click the project dropdown on the right
3. Ensure that your correct project is selected
4. Click "OAuth consent screen" on the left side of the screen (below "Credentials")
5. Under "Test users" there is a button called "+ ADD USERS"
6. Type the email of the account you will be testing with, press enter, then click save.
7. It work now!

**Comment by yo-honey** [comment]
thanks, this works
