### ISSUE TITLE
HTTPError 403: Forbidden

### ISSUE THREAD

**Issue by voytakaleta** [aldacco/drive-login#16]
Hi @aldacco 

![Activation](https://github.com/user-attachments/assets/b4d3b185-2579-4af2-bdcf-e85c773178a5)
 
My login seems to be successful but after entering the PIN code, this error header pops up on KODI

"Unable to retrieve the owner information:
HTTP Error 403: Forbidden
Please try again
"

Thank you very much for any advice!

**Comment by aldacco** [comment]
The `HTTPError 403: Forbidden` usually occurs when the Google Drive or Google Photos API is not enabled. To resolve this issue, ensure that both APIs are enabled in your Google Cloud Console project:

1. Go to the **[Google Cloud Console](https://console.cloud.google.com/)**.
2. In the navigation panel, select **APIs & Services > Library**.
3. Search for and enable the following APIs:
   - **Google Drive API**
   - **Google Photos Library API**
4. Double-check your OAuth settings to ensure that access to these APIs is correctly authorized.

This should resolve the authorization error.
