### ISSUE TITLE
Unable to retrieve the owner information: HTTP Error 403: Forbidden Please try again.

### ISSUE THREAD

**Issue by DebankurMandal** [aldacco/drive-login#17]

**Comment by DebankurMandal** [comment]
After succesfully following your steps and after sucessfull login,  a prompt pops up in Kodi which says "Unable to retrieve the owner information: HTTP Error 403: Forbidden Please try again." Please help us to solve this issue

**Comment by aldacco** [comment]
maybe [https://github.com/aldacco/drive-login/issues/16#issuecomment-2495933109](url)
