### ISSUE TITLE
Erro 401: invalid_client

### ISSUE THREAD

**Issue by cabrunasx** [aldacco/drive-login#19]
When I try to log in with the Kodi code this error appears and I can't log in

**Comment by aldacco** [comment]
### Check and Update Environment Variables

1. **Verify Environment Variables**:
   - Make sure the environment variables are set correctly based on the version you're using (e.g., `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET`).
   - If you're using the **latest version**, ensure that the variables are up to date according to the new requirements.

2. **Update Environment Variables**:
   - If you need to update any variables, go to the [Vercel Dashboard](https://vercel.com/dashboard).
   - Navigate to **Settings > Environment Variables** and add/update the necessary values.

3. **Redeploy Your Application**:
   - After updating the environment variables, **redeploy your application** for the changes to take effect.
   - You can trigger a redeploy by pushing a new commit or clicking **Deploy** in the Vercel dashboard.
