### ISSUE TITLE
Issue After Login

### ISSUE THREAD

**Issue by Varun23102002** [aldacco/drive-login#4]
Hello Bro there is issue after login it's working but we don't use for few minutes it shows Google drive server unavailable 
![IMG_20240521_154821_429](https://github.com/aldacco/drive-login/assets/99336510/403c6f7e-5364-4ac5-a2e5-57299ccaaa62)

**Comment by aldacco** [comment]
Delete all your accounts and try to log in again.

**Comment by Varun23102002** [comment]
@aldacco ok buddy and thanks for your efforts and reply

**Comment by thomasdoodle1** [comment]
I am getting this error when logging in through edu account
![image](https://github.com/aldacco/drive-login/assets/71864978/42cd86bc-b280-4e12-aa3e-40f2e4347c39)

**Comment by Varun23102002** [comment]
Hey bro help me with redis connection my mail id is varunbh307@gmail.com

**Comment by aldacco** [comment]
> Hey bro help me with redis connection my mail id is [varunbh307@gmail.com](mailto:varunbh307@gmail.com)

Create a redis database with https://upstash.com/

**Comment by Varun23102002** [comment]
@aldacco bro it works 
Thanks for your hardwork and dedication. I really appreciate your hardwork thanks a lot again 😁
