### ISSUE TITLE
Google Drive - The server is temporary unavailable for this operation.

### ISSUE THREAD

**Issue by greatestradioshow** [aldacco/drive-login#6]
Hi @aldacco ,

I followed the steps as mentioned:
> Google Projecte created
> Vercel App created and variables added (Import Third-Party Git Repository)
> Redis created
> Vercel URL in Kodi added

But when I try to add my account, I just get an error message in Kodi:
```
Google Drive
The server is temporary unavailable for this operation.
Please try again later.
```

Do you have an idea what I could have done wrong (moste likely)?
Or if you need any logs, please let me know.

Thanks in advance.

**Comment by aldacco** [comment]
Most likely the redis connection string is wrong, check it and update that environment variable and redeploy.
Share your domain so we can check it too.

**Comment by aldacco** [comment]
> Hi @aldacco ,
> 
> I followed the steps as mentioned:
> 
> > Google Projecte created
> > Vercel App created and variables added (Import Third-Party Git Repository)
> > Redis created
> > Vercel URL in Kodi added
> 
> But when I try to add my account, I just get an error message in Kodi:
> 
> ```
> Google Drive
> The server is temporary unavailable for this operation.
> Please try again later.
> ```
> 
> Do you have an idea what I could have done wrong (moste likely)? Or if you need any logs, please let me know.
> 
> Thanks in advance.

Most likely the redis connection string is wrong, check it and update that environment variable and redeploy.
Share your domain so we can check it too.

**Comment by greatestradioshow** [comment]
My domain:
https://kodi-drive-login-tfab.vercel.app/

The Redis URL I see:
redis-cli --tls -u redis://default:********@trusting-ibex-61134.upstash.io:6379

For the env variable, I changed it to (and the ******** changed for the real PW):
redis://default:********@trusting-ibex-61134.upstash.io:6379


You see something strange with my setup?

**Comment by aldacco** [comment]
Hey! It looks like you need to switch from redis:// to rediss:// for your Redis connection URL to enable SSL/TLS. Update your env variable to:

rediss://default:********@trusting-ibex-61134.upstash.io:6379

**Comment by aldacco** [comment]
> Hey! It looks like you need to switch from redis:// to rediss:// for your Redis connection URL to enable SSL/TLS. Update your env variable to:
> 
> rediss://default:********@trusting-ibex-61134.upstash.io:6379
> and redeploy your project, so that the changes will be applied.

**Comment by greatestradioshow** [comment]
This did the trick! Perfect, now it works. Thanks a lot.
